### PR TITLE
Add telemetry aggregation job.

### PR DESCRIPTION
**Pull request by vitillo**
This change is [Reviewable](https://reviewable.io/reviews/vitillo/telemetry-airflow/11)

### CODE REVIEW

**Comment by maurodoglio** [comment]
Review status: 0 of 2 files reviewed at latest revision, 3 unresolved discussions.

---

*[dags/telemetry_aggregates.py, line 21 \[r1\]](https://reviewable.io:443/reviews/vitillo/telemetry-airflow/11#-KLQ8ogEDZUM2rXl-5hY:-KLQ8ogFzX3gl6MeAves:-311657595) ([raw file](https://github.com/vitillo/telemetry-airflow/blob/aecea9ddc98f7e6864b59a54ae343d0c91582fe8/dags/telemetry_aggregates.py#L21)):*
> ```Python
>                       job_name = "Telemetry Aggregate View",
>                       instance_count = 6,
>                       env = {"date": "{{ ds_nodash }}"},
> ```

does ds_nodash mean 'yesterday date without dashes' ?

---

*[jobs/telemetry_aggregator.py, line 8 \[r1\]](https://reviewable.io:443/reviews/vitillo/telemetry-airflow/11#-KLQ9q5Vr_cwldXlFvQX:-KLQ9q5Vr_cwldXlFvQY:-1182527565) ([raw file](https://github.com/vitillo/telemetry-airflow/blob/aecea9ddc98f7e6864b59a54ae343d0c91582fe8/jobs/telemetry_aggregator.py#L8)):*
> ```Python
> from mozaggregator.db import submit_aggregates
> 
> root = logging.getLogger()
> ```

I would use __name__ to define the logger. Don't know if this is much useful in the context of a airflow job, but I don't see why not.

---

*[jobs/telemetry_aggregator.py, line 9 \[r1\]](https://reviewable.io:443/reviews/vitillo/telemetry-airflow/11#-KLQ841mbzZgRG8L1Htb:-KLQ841nWsZvXiyr5Sxw:75616874) ([raw file](https://github.com/vitillo/telemetry-airflow/blob/aecea9ddc98f7e6864b59a54ae343d0c91582fe8/jobs/telemetry_aggregator.py#L9)):*
> ```Python
> 
> root = logging.getLogger()
> root.setLevel(logging.INFO)
> ```

This seems to be already defined here https://github.com/apache/incubator-airflow/blob/3ffa656d97a8e3fcf6e3498ab0a1c882146dc3f5/airflow/bin/cli.py#L58

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vitillo/telemetry-airflow/11)*

**Comment by maurodoglio** [comment]
Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vitillo/telemetry-airflow/11)*

**Comment by vitillo** [comment]
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[dags/telemetry_aggregates.py, line 21 \[r1\]](https://reviewable.io:443/reviews/vitillo/telemetry-airflow/11#-KLQ8ogEDZUM2rXl-5hY:-KLQDwuOgdL86kP4WpIP:306296796) ([raw file](https://github.com/vitillo/telemetry-airflow/blob/aecea9ddc98f7e6864b59a54ae343d0c91582fe8/dags/telemetry_aggregates.py#L21)):*
<details><summary><i>Previously, maurodoglio (Mauro Doglio) wrote…</i></summary>
> does ds_nodash mean 'yesterday date without dashes' ?
</details>
It means the current date without dashes.

---

*[jobs/telemetry_aggregator.py, line 9 \[r1\]](https://reviewable.io:443/reviews/vitillo/telemetry-airflow/11#-KLQ841mbzZgRG8L1Htb:-KLQE4MaWE0kH3Ly6oKP:-1535541340) ([raw file](https://github.com/vitillo/telemetry-airflow/blob/aecea9ddc98f7e6864b59a54ae343d0c91582fe8/jobs/telemetry_aggregator.py#L9)):*
<details><summary><i>Previously, maurodoglio (Mauro Doglio) wrote…</i></summary>
> This seems to be already defined here https://github.com/apache/incubator-airflow/blob/3ffa656d97a8e3fcf6e3498ab0a1c882146dc3f5/airflow/bin/cli.py#L58
</details>
That code, which runs on the Airflow service, is not related with this file which is invoked on the master node of the EMR cluster.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vitillo/telemetry-airflow/11)*

**Comment by maurodoglio** [comment]
Review status: 1 of 2 files reviewed at latest revision, 3 unresolved discussions.

---

*[jobs/telemetry_aggregator.py, line 9 \[r1\]](https://reviewable.io:443/reviews/vitillo/telemetry-airflow/11#-KLQ841mbzZgRG8L1Htb:-KLQFGcsNbIyD216DOGR:1100206530) ([raw file](https://github.com/vitillo/telemetry-airflow/blob/aecea9ddc98f7e6864b59a54ae343d0c91582fe8/jobs/telemetry_aggregator.py#L9)):*
<details><summary><i>Previously, vitillo (Roberto Agostino Vitillo) wrote…</i></summary>
> That code, which runs on the Airflow service, is not related with this file which is invoked on the master node of the EMR cluster.
</details>
oh ok, so I guess you need to setup a log handler as well?
something like
```python
logger = logging.getLogger(__name__)
sh = logging.StreamHandler()
logger.addHandler(sh)
```
and potentially add a formatter.
I feel like we should have something more centralized, that adds a handler and eventually a formatter to the root handler so that we don't have to set it up on every job. Of course this could be part of a followup patch :smile_cat:  

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vitillo/telemetry-airflow/11)*

**Comment by vitillo** [comment]
Review status: 1 of 2 files reviewed at latest revision, 3 unresolved discussions.

---

*[jobs/telemetry_aggregator.py, line 8 \[r1\]](https://reviewable.io:443/reviews/vitillo/telemetry-airflow/11#-KLQ9q5Vr_cwldXlFvQX:-KLQNBFhr6wIJXyq31CY:-499146009) ([raw file](https://github.com/vitillo/telemetry-airflow/blob/aecea9ddc98f7e6864b59a54ae343d0c91582fe8/jobs/telemetry_aggregator.py#L8)):*
<details><summary><i>Previously, maurodoglio (Mauro Doglio) wrote…</i></summary>
> I would use __name__ to define the logger. Don't know if this is much useful in the context of a airflow job, but I don't see why not.
</details>
Done.

---

*[jobs/telemetry_aggregator.py, line 9 \[r1\]](https://reviewable.io:443/reviews/vitillo/telemetry-airflow/11#-KLQ841mbzZgRG8L1Htb:-KLQJnD2_pimt2wxYGbF:1998876552) ([raw file](https://github.com/vitillo/telemetry-airflow/blob/aecea9ddc98f7e6864b59a54ae343d0c91582fe8/jobs/telemetry_aggregator.py#L9)):*
<details><summary><i>Previously, maurodoglio (Mauro Doglio) wrote…</i></summary>
> oh ok, so I guess you need to setup a log handler as well?
> something like
> ```python
> logger = logging.getLogger(__name__)
> sh = logging.StreamHandler()
> logger.addHandler(sh)
> ```
> and potentially add a formatter.
> I feel like we should have something more centralized, that adds a handler and eventually a formatter to the root handler so that we don't have to set it up on every job. Of course this could be part of a followup patch :smile_cat:  
</details>
Yeah, that makes sense.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vitillo/telemetry-airflow/11)*

**Comment by maurodoglio** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vitillo/telemetry-airflow/11#-:-KLQaEoOhx0pCfaooXQo:1417088721)*

**Pull request merged**
