### PR TITLE
Add ELB creation and HTTPS support

### PR DESCRIPTION
**Pull request by mreid-moz**
This adds the configuration needed to support HTTPS on workflow.t.m.o. Per Wesley's recommendation, I set up a separate security group for the ELB and ECS instances, with references between them.

I tested the security groups part, but I have not redeployed the entire cluster to make sure it all works.

---
This change is [Reviewable](https://reviewable.io/reviews/vitillo/telemetry-airflow/7)

### CODE REVIEW

**Comment by vitillo** [comment]
Review status: 0 of 4 files reviewed at latest revision, 1 unresolved discussion.

---

*[ansible/deploy_aws.yml, line 14 \[r1\]](https://reviewable.io:443/reviews/vitillo/telemetry-airflow/7#-KL1mQoOZA4g1SnQ4zz1:-KL1mQoOZA4g1SnQ4zz2:-493467305) ([raw file](https://github.com/vitillo/telemetry-airflow/blob/014de36426d4b265f77b654460532eab95cd8512/ansible/deploy_aws.yml#L14)):*
> ```YAML
>       s3: bucket={{airflow_bucket}} region={{region}} object=steps/airflow.sh src=ansible/files/spark/airflow.sh mode=put
> 
>     - ec2_group_facts:
> ```

Please remove `library/ec2_group_facts.py` if it's no longer needed.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vitillo/telemetry-airflow/7)*

**Comment by vitillo** [comment]
Reviewed 4 of 4 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vitillo/telemetry-airflow/7)*

**Comment by mreid-moz** [comment]
Right, so I've now tested this and it seems to work fine. There is one caveat which is that the `ecs_cluster` and `ecs_service` modules need to be slightly tweaked, otherwise you encounter the following error:
`"Exception describing service 'telemetry-airflow' in cluster 'telemetry': No JSON object could be decoded"`

The change is simple, but I'm not entirely sure why it's needed.  Simply uncomment the commented-out line [here](https://github.com/ansible/ansible-modules-extras/blob/0e4a023a7e883743e92ddfcd097b3a60d86b1608/cloud/amazon/ecs_cluster.py#L125) and comment out (or remove) the next few lines. Same with 

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/vitillo/telemetry-airflow/7#-:-KL28iIH9Q-ekHXWFklg:-1188896735)*

**Comment by mreid-moz** [comment]
Argh, I take it back. I must've checked before the new stack got swapped in. Not currently working.

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/vitillo/telemetry-airflow/7#-:-KL2AapMXNb9uh2dxaZd:-1428990207)*

**Comment by mreid-moz** [comment]
Ok, with this latest set of changes, everything appears to work!  One important note is that I renamed the `test` environment to `stage`, and cleared out the `production` config to avoid confusion.  We can re-add `production` when we finalize how it should look. The [currently-running airflow](https://workflow.telemetry.mozilla.org/) was provisioned from this branch.

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/vitillo/telemetry-airflow/7#-:-KL2_yFvEo31p0aM40n6:1680366096)*

**Comment by vitillo** [comment]
Reviewed 4 of 4 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vitillo/telemetry-airflow/7)*

**Pull request merged**
